###               ____                    _
#  ____ _____  __/ ___\_   _  __ _ _ ____| |
# / __// _ \ \/ / /  _| | | |/ _' | '_/ _' |
# \__ \  __/>  <\ \_| | |_| | (_) | || (_) |
# /___/\___/_/\_\\____/\___/ \__,_|_| \__,_|
#
#   PROTECTS YOUR ANUS SINCE: 27 Dec. 2016
###
name: SexGuard
main: sex\guard\Manager
version: 1.1.7
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
- 3.0.0-BETA
- 3.0.0-BETA1
- 3.0.0-BETA2
- 3.0.0-BETA3
- 3.0.0-BETA4
- 3.0.0-BETA5
- 3.0.0-ZAEBALI
- 4.0.0

author: sex_KAMAZ
website: https://vk.com/infernopage

load: POSTWORLD

commands:
  rg: []